all the desires are designed as inputs, why?  it is almost like market
economy if i were to design a system that satisfy all your desires,
then it will be hard. and also what is the point.  desires serves with
a purpose

market is just an acknowledgement of that and embracement of that.

when designing the human race, the desire of one particular human
isn't all that important. what is important is the satisfaction of the
collective desire. 

the satisfaction of the collective desire needs to be aligned with the
benefits of the race.

market is a recognition of that.

how to design desires, that is kind of like incentive engineering. and
it is perhaps very important.

maybe start from fundamental is important, there are desires to grow,
desires to mate, desires to get full, desires to live. desires for
great food (is that a desire? why not just delicious?)

- https://en.wikipedia.org/wiki/Philosophy_of_desire
  In philosophy, desire has been identified as a philosophical problem
  since Antiquity. In Plato's The Republic, Socrates argues that
  individual desires must be postponed in the name of the higher
  ideal. 

  In buddism
  craving is thought as the root of all sufferings, is buddism
  anti-human? By eliminating craving, a person can attain ultimate
  happiness, or Nirvana. But does this contradict with the
  continuation of the human being as a race?

The increased ability of individual might jeopardize the collective
well beings of a race.

reason and the "right" desire. that is a incentive as well.

desire is the craving for pleasure. most suggest to control it with
reasoning. some suggest to eliminate them all together.
The suffering ends when the craving and desire ends, the human being
ends too.

big data, how much irational? how much damage can it make?

In his Ethics, Baruch Spinoza declares desire to be "the very essence
of man,"

wow:
"desire's raison d'être is not to realize its goal, to find full
satisfaction, but to reproduce itself as desire." <- Slavoj Žižek

when god invents people, he has two choices, make something very
machine like, it does a bunch of stuff and will last for certain
amount of time. contrary to that, he break the whole thing up into
smaller pieces and plants incentives driven by desires, a more soft
approach i would say. small things might fall off the cracks but it is
more resillient to change of circumstances. as long as desires are
aligned there will be a way out.

Precondition, man has intelligence. why is this important? isn't
intelligence the consequence of the struggling for satisfying desires?
if that is the case, then the "desire" architecture is actually
fundamental to everything.

Limitations of desire, or perhaps desire is always short
sighted. maybe it is feelings of fear for death is too strong, anyways
there must be an explanation when it comes to convenience over privacy
and short time preferences.


eatern society and western society, people focus on different things,
maybe eastern ones have some advantage in the long run.

** from the podcast

shall i distinguish the basic needs and desire (or wants) since the
latter seems to be the cause of more conflicts.

lost the sense of self.

points to a small fraction of people <-> ritual callibalism all over
the world.

Jesus is a typical example of the collective sacrifice around the
world. It is in people's collective desire. This collective desire
might be a symptom to survive as well. 

So it is not just about individual desire, it is also the collective
desire. 


desire to emitate is perhaps one of the fundamental human nature

this theory is so interesting
Basically, the big brain of human means that a prolonged period of
peace needs to be in place and if we accept that mimical desire is at
the core of humanity and it would quickly evolve with conflicts, then
externalizing it once in a while through the means of sacrifice or
sacred is neccessary. this is built into the core of human beings.